# Receiver Status (flags)

# Error flag
bool error

# Temperature Status (error)
bool temp_err

# Voltage Supply Status (error)
bool vol_err

# Antenna Power Status (error)
bool ant_pwr_err

# COM1 buffer overrun flag (error)
bool com1_ovr_err

# COM2 buffer overrun flag (error)
bool com2_ovr_err

# COM3 buffer overrun flag (error)
bool com3_ovr_err

# RF1 AGC status (error)
bool rf1_err

# Position solution flag (error)
bool pos_sol_err

# Position fixed flag
bool pos_fixed

# Clock steering status (error)
bool clk_st_err

# Clock model flag (error)
bool clk_err

# OEMV card external oscillator flag
bool osc_ext

# Software resource (error)
bool soft_err

# Auxiliary 3 status event flag
bool aux3_err

# Auxiliary 2 status event flag
bool aux2_err

# Auxiliary 1 status event flag
bool aux1_err
